default['laravel']['path'] = '/home/ubuntu/apps/core'
default['laravel']['repo'] = 'gitlab@gitlab.owlgrin.com:horntell/core.git'
default['laravel']['branch'] = 'master'
default['laravel']['env'] = 'production'
default['laravel']['config_repo'] = 'gitlab@gitlab.owlgrin.com:horntell/configs.git'
default['laravel']['config_branch'] = 'core'